# ~/.config/alacritty/alacritty.toml

[window]
# Equivalent to wezterm "RESIZE" â†’ border but no title bar
decorations = "None"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[colors.cursor]
text = "0x002b36"
cursor = "0x839496"

[colors.normal]
black   = "0x073642"
red     = "0xdc322f"
green   = "0x859900"
yellow  = "0xb58900"
blue    = "0x268bd2"
magenta = "0xd33682"
cyan    = "0x2aa198"
white   = "0xeee8d5"

[colors.bright]
black   = "0x002b36"
red     = "0xcb4b16"
green   = "0x586e75"
yellow  = "0x657b83"
blue    = "0x839496"
magenta = "0x6c71c4"
cyan    = "0x93a1a1"
white   = "0xfdf6e3"

[keyboard]
bindings = [
  # Option (Alt) + Left = move back a word
  { key = "Left",  mods = "Alt", chars = "\u001bb" },
  # Option (Alt) + Right = move forward a word
  { key = "Right", mods = "Alt", chars = "\u001bf" },

  # Command + Left = move to beginning of line
  { key = "Left",  mods = "Command", chars = "\u0001" }, # Ctrl-A
  # Command + Right = move to end of line
  { key = "Right", mods = "Command", chars = "\u0005" },  # Ctrl-E
  { key = "Back", mods = "Command", chars = "\u0015" }
]

[selection]
save_to_clipboard = true
